%% this code calculates the knee kinematics in both the original, digitised coordinate frame and the optimised coordinate frame
clc;clear; close all;
profile on;
diary("log.txt"); % Creates a log. Important for checking which runs failed!!
addpath('spm');
addpath(genpath('./lib'))
%% Load in the Specimen folder
defaults;

% State cfg file is used to create the transforms.
disp("Pick the folder with all the specimens")
root = uigetdir(".", "Pick the folder with all specimens");
experiment = Experiment(root, config);
trajectories = experiment.Trajectories;

%%
trajectories.plot_tibia();

%%
[ap_flex, ap_ext] = trajectories ...
    .ap() ...
    .filter_signal("jcs") ...
    .exclude_specimen("3")...
    .split_flex_ext();
ap_flex.print_to_file(root);
%% Neutral Path

trajectories...
    .path()...
    .filter_signal("jcs")...
    .average()...
    .split_flex_ext()...
    .print_to_file(root)...
    .plot("posterior");

%% Stability Envelopes
[ap_flex, ap_ext] = trajectories ...
    .ap() ...
    .filter_signal("jcs") ...
    .exclude_specimen("3")...
    .average() ...
    .split_flex_ext();
ap_flex.print_to_file(root);
ap_flex.plot("posterior");

trajectories ...
    .ie()...
    .filter_signal("jcs")...
    .average()...
    .split_flex_ext()...
    .plot("internal_rotation");